version: "3.8"

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD=pAssw0rd
    container_name: redis_server
    ports:
      - 6379:6379
    networks:
      - redis-network
    hostname: my-redis

networks:
  redis-network:
    name: redis-network
    driver: bridge