version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbitmq-network
    hostname: my-rabbit
    volumes:
      - ./etc/definitions.json:/etc/rabbitmq/definitions.json
networks:
  rabbitmq-network:
    name: rabbitmq-network
    driver: bridge