# Generated by Django 3.1.5 on 2021-01-09 23:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210109_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='order_details',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.orderdetails'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
