version: "3.8"

services:
  database:
    container_name: ecommerce-orders-database
    image: postgres:12.1
    ports:
      - 5433:5432
    volumes:
      - ecommerce-orders-database:/var/lib/postgresql/data
    networks:
      - order-service-network

  server:
    build:
      context: ./server
    container_name: ecommerce-orders-server
    image: ecommerce-orders-server
    command: ["bash", "start.sh"]
    depends_on:
      - database
    environment:
      - PGDATABASE=ecommerce
      - PGUSER=ecommerce
      - PGPASSWORD=ecommerce
      - PGHOST=ecommerce-orders-database
    ports:
      - 8001:8000
    volumes:
      - ./server:/usr/src/app
      - static:/usr/src/app/static
    networks:
      - order-service-network

  worker:
    image: ecommerce-orders-server
    restart: on-failure
    command: >
      sh -c "cd ecommerce && celery -A ecommerce.celery worker -l info"
    depends_on:
      - server
      - database
    networks:
      - order-service-network

  reverse-proxy:
    build:
      context: ./reverse-proxy
    container_name: ecommerce-reverse-proxy
    depends_on:
      - server
    ports:
      - 8080:80
    restart: always
    volumes:
      - static:/usr/src/app/static
    networks:
      - order-service-network

volumes:
  ecommerce-orders-database:
  static:

networks:
  order-service-network:
    external:
      name: rabbitmq-network
