# Generated by Django 3.1.5 on 2021-01-09 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinventory',
            name='product_id',
        ),
    ]
